const ROLES = {
  ADMIN: 'ADMIN',
  HR_USER: 'HR_USER',
  TRAINING_MANAGER: 'TRAINING_MANAGER',
  EMPLOYEE: 'EMPLOYEE',
};

const SIGNUP_ROLES = [ROLES.EMPLOYEE, ROLES.HR_USER, ROLES.TRAINING_MANAGER];

const STAFF_ROLES = [ROLES.ADMIN, ROLES.HR_USER, ROLES.TRAINING_MANAGER];

const ROLE_LABELS = {
  [ROLES.EMPLOYEE]: 'Employee',
  [ROLES.HR_USER]: 'HR User',
  [ROLES.TRAINING_MANAGER]: 'Training Manager',
  [ROLES.ADMIN]: 'Admin',
};

module.exports = { ROLES, SIGNUP_ROLES, STAFF_ROLES, ROLE_LABELS };
